source 'https://github.com/CocoaPods/Specs.git'

pod 'UIColor+Hex', :git => 'https://github.com/Inferis/UIColor-Hex.git'
pod 'SVWebViewController', :git => 'https://github.com/jonathontoon/SVWebViewController.git'
pod 'UITableView-StickyHeader', :git => 'https://github.com/namanhams/UITableView-StickyHeader.git'
